version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend
  
  api:
    depends_on:
      - mongodb
    build: ./api
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend

  frontend:
    depends_on:
      - api
    build: ./client
    restart: unless-stopped
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    networks:
      - backend

volumes: 
  db:
networks:
  backend: